import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import { FamilyTree } from '../components/FamilyTree/FamilyTree'
import { FAMILY_TREE_MODE } from "../enums"
import React from 'react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>पौडेल परिवार</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script id='raphael' src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js" strategy={'beforeInteractive'} />
      <Script id='treant' src="https://cdnjs.cloudflare.com/ajax/libs/treant-js/1.0/Treant.min.js" strategy={'beforeInteractive'} />

      <div className="container text-center font-Mukta py-8">
        <main>
          <h1 className='text-8xl mb-16 text-black'>
            पौडेल परिवार
          </h1>

          <p className='text-2xl mb-8 text-black font-Nunito'>
            <span className="text-3xl">
              Welcome to Poudel family.
            </span>
            <br />
            <br />
            This page contains all the general information on Poudel family.&nbsp;
            It aims to serve as reference to newer generations to know more about their family history,&nbsp;family members.
          </p>
        </main>
      </div>

      <div className="px-0 md:px-8 mx-auto my-8">
        <FamilyTree mode={FAMILY_TREE_MODE.MIN} />
      </div>

    </div>
  )
}

export default Home
